---
title: "Laboratorio_1"
author: "Carlos_Alvarado"
date: "2022-08-03"
output: rmarkdown::github_document
---
### Librerias
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(readr)
library(tidyverse)
library(tidytext)
```

### Leer los xlsx
```{r}
excel01 <- readxl::read_excel('01-2018.xlsx')
excel02 <- readxl::read_excel('02-2018.xlsx')
excel03 <- readxl::read_excel('03-2018.xlsx')
excel04 <- readxl::read_excel('04-2018.xlsx')
excel05 <- readxl::read_excel('05-2018.xlsx')
excel06 <- readxl::read_excel('06-2018.xlsx')
excel07 <- readxl::read_excel('07-2018.xlsx')
excel08 <- readxl::read_excel('08-2018.xlsx')
excel09 <- readxl::read_excel('09-2018.xlsx')
excel10 <- readxl::read_excel('10-2018.xlsx')
excel11 <- readxl::read_excel('11-2018.xlsx')
```

### Merge de los datasets
```{r}
generate_df <-  function(tamanio){ return(
    data.frame(
      mes = sample(1, size = tamanio, replace = TRUE)
    )
  )
}



```



### Exportación del archivo
```{r}
#exportaar el excel
write_excel_csv2(excel, "exportar_excel.xls", delim = ",")
```

